### ISSUE TITLE
Addition of Web Crawler 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#11]
Webscraper needs to have some sort of feed-in from URLs to actually do its job. 

I could hand-feed the webscraper, but that would be tedious and impractical. 

A web crawler should be able to grab a bunch of website URLs for me and store them somewhere that my program can read from for the webscraper.

**Comment by jazzij** [comment]
Is this what you are planning to use the sitemap for?

**Comment by jazzij** [comment]
Please also link this to the code that you're committing. (In your commit description, add the commit number. For example: "#11 Added excel spreadsheet"
