### ISSUE TITLE
Major: User Interface

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#13]
User interface needs to be created so that the user can actually interact with a mobile app. At this time, Kivy seems like the best bet for that and that's my plan. 

Sketches for that can be found in my deliverables.

**Comment by alfarozavalae** [comment]
I see in your week 6 code PR that you created the tkinter window. Do you plan to continue making changes to it or is it done? 
If it is done, you can close this issue. if not, keep it opened while you keep working on it.
