### ISSUE TITLE
D5: End-to-end testing

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#22]
This issue is to track unit testing for the D5 assignment. 
Bugs/Issues found through end to end testing: 
#31 (fixed) 
#30 (fixed) 
#29 (not enough time to fix 
#24 (in progress) 
#34 (not enough time to fix)

**Comment by schweinsbergs** [comment]
Edited this to be an end-to-end test. Upon further reflection, this is what I've been doing to test my project and how I've been finding most of my bugs.

**Comment by alfarozavalae** [comment]
If you have created issues related to this type of testing make sure to link them here

**Comment by schweinsbergs** [comment]
Added them, thanks!
