### ISSUE TITLE
D5: Cognitive walkthrough 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#23]
This is a tracker for the other part of my D5, cognitive walkthrough. 
Bugs/issues found through cognitive walkthrough: 
#32 (fixed) 
#28 (fixed) 
#25 (fixed)

**Comment by alfarozavalae** [comment]
If you have created issues related to this type of testing make sure to link them here

**Comment by schweinsbergs** [comment]
Updated, thanks!

**Comment by schweinsbergs** [comment]
Seems that all of the problems I ran into during my cognitive walkthrough are fixed!
