### ISSUE TITLE
D5: End to End:  >100% Matches 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#24]
The dataframe ingredients strings can be searched more than once per to create nonsensical percentage matches. 

For example: 

User input = ['1', 'cup', 'grain'] 
Dataframe = ['1 cup starch', 'grain'] 

The match list would produce: ['1', 'cup', 'grain'], which generates a 3/2 match.

**Comment by schweinsbergs** [comment]
Potential solution is using shallow copy and detaching what's matched from it and putting it into the match list.

**Comment by alfarozavalae** [comment]
mmm what if when taking user input you specifically tell the user to input just ingredients and not units of measure? 
You can have input validation to make sure they are not entering "cup" "1", etc and this would prevent the issue from happening. 
This is honestly a simply way of trying to solve this issue considering the time limitations. 

Another option would be creating a list of common words to not match (example: cup, 1, tablespoon, etc) and checking if the input is there to discard it. Afterwards, running the matching function with just the actual ingredients.

**Comment by schweinsbergs** [comment]
I LOVE your style. 
That's a simple fix that works for me. I'll try to implement it next bug fix session.

**Comment by schweinsbergs** [comment]
Did something extremely simple: Values over 100% cannot be displayed. This needs a better fix later, but I'm juggling 3 finals. :S
