### ISSUE TITLE
Addition of URL dataframe columns 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#25]
Want to append the URL and the matches for both debugging purposes and for user's ease of access. Putting this here so I don't forget.

**Comment by schweinsbergs** [comment]
Tried to use the webscraper's link option for adding onto the dataframe, but it looks like it's pulling html to do that and uh... that's not human friendly. I'm just going to try to attach the url that's in the excel sheet to the dataframe instead of using the webscraper for it, seems more intuitive at this point.

**Comment by schweinsbergs** [comment]
Splitting this issue into 2, addition of matches isn't trivial. Yeehaw. 

Fixed by most recent push.

**Comment by alfarozavalae** [comment]
Are you trying to create a link to each individual recipe by appending the link and the selection?

**Comment by alfarozavalae** [comment]
I see that you broke this into two separate issues. I think that's a good idea. 
One issue is for adding the URL dataframe columns but what is the second issue?

**Comment by schweinsbergs** [comment]
Sorry! 
@alfarozavalae  I created a link to each individual recipe, yep, that part's taken care of. 

Second issue is for adding the matches in, which I found isn't trivial because the way I track my matches is through a series of true and falses.
