### ISSUE TITLE
D5: User testing: Add options that aren't vegan 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#28]
It's been fun testing with just vegan recipes, but it's time to add more recipes for the users sake. Many users expressed wanting to use meat... Me too.

**Comment by schweinsbergs** [comment]
Issue #29 is throwing a wrench in this one.

**Comment by schweinsbergs** [comment]
#29 has made a really interesting issue for me. I'm gonna scrape non-vegan recipes for now with the some 350 slots I have.

**Comment by alfarozavalae** [comment]
You indicated you fixed this in issue #28. What other recipe types did you add? Is it working?

**Comment by schweinsbergs** [comment]
@alfarozavalae 
I added recipes from a non-vegan site for now with the limited ~350 spaces I have, since almost every test user didn't want vegan stuff and I just threw in the vegan stuff because it was the first successful scrape. It's working-- I wanted to have *more* recipes, but I'm running into that error in #28.
