### ISSUE TITLE
D5: End to End Testing: Division by 0 

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#30]
ZeroDivisionError: division by zero 
Trivial bug (I always say this and then eat my words) 

Line 145: fraction = (matches.count(True) / len(ingredientList)) * 100 needs a catch for if it's dividing by 0

**Comment by schweinsbergs** [comment]
Bug's fixed, is in the week 6 check in push.

**Comment by alfarozavalae** [comment]
I have reviewed the code for this and it looks good!
You can go ahead and close this issue
