### ISSUE TITLE
D5: End-to-end: NoneType

### ISSUE THREAD

**Issue by schweinsbergs** [Berea-CS-Courses/capstone-project-schweinsbergs#31]
While scraping, encountered the following error: 
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by schweinsbergs** [comment]
There were empty values in the excel sheet that were making my program scrape nothing, and then throw a tantrum because it wasn't scraping anything. Fixed in last push.

**Comment by alfarozavalae** [comment]
Just to confirm, your function called _get_ordered_configuration_items(self) in your parser.py file is the one that accomplishes this right? 
Go ahead and close this issue now that this is fixed.

**Comment by schweinsbergs** [comment]
I unfortunately don't know what you're talking about. I've been working out the recipeApp.py file, I think that's a dependency you're looking at
